### ISSUE TITLE
Icon Request: Visible SR Rescues/Rescued with light background color

### ISSUE THREAD

**Issue by fetus-hina** [hacceuee/s3-pixel-icons#17]
I think this is related to what you were referring to in commit b7a1facfe91abbfcba52a695be146dd1c2e237ba, the current SR Rescues/Rescued icons are hardly visible on light background color.
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/90319b22-300a-4920-9536-34e764bf2afa)

Reference: on dark background
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/be14106e-8d1c-4df3-8938-0f437440a597)

So, it would be nice to have another version created in a certain visible color in __addition__ to the current icon.
(The current icons are very useful for use in [dark areas, such as the results image](https://s3-img-gen.stats.ink/salmon/en-US/2535c6b6-8b58-4783-83e1-59be13c76345.jpg), and I expect that they will be created separately.)

The following image is a tentative one I have in mind. It is not practical, but I think it is good enough for discussion.
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/b1fddad2-34ef-42af-bade-5f4b791a3439)

It would be great if one image could be used for both light and dark themes, but even if not, I can send different images depending user theme settings.

**Comment by hacceuee** [comment]
I can think of a couple of solutions: 

1) I can upload a file with the squid (and flag, for SR) as a layer, and the ink a separate layer. This may allow you to programmatically adjust the brightness of the squid, and adjust the hue of the ink as needed. 

2) I could put a low-opacity flag so it stands out, despite the background color: 
![50 on white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/4c658b76-b182-4372-93dc-202ef892d026)
![50 on 50](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/76a26d28-7906-4e96-a7f3-0c18037dee8e)
![50 on black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/4d860849-a63b-4314-9f0a-f5c0e82796b6)

3) I could put a solid-opacity neutral flag: 
![grey on white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/19ecbe03-7b54-4b8f-a303-57b72b90c86f)
![grey on 50](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/1ca40af8-7b92-490b-ac19-326036c6f438)
![grey on black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/4cd85b99-b3cb-4fdb-9fda-aba77ac7cf10)

4) I could add on outline (can also do black image with white background): 
![outilne on white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/d02bd1bd-7cf9-4558-a3b5-66f5d26e6413)
![outline on 50](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/65cbf22e-15a3-4c31-8ced-722d05a6b3ea)
![outline on black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/abf236be-47a5-466a-a392-e09f15521fc0)

4) I could assign a color (albeit a better one this this): 
![color on white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/3ca0d982-7d24-45dc-a2cf-e63b8b469543)
![color on grey](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/a5d2df35-aa0b-4906-9e23-67bf5692a385)
![color on black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/928af90e-44b9-413e-9f00-84a38da318cf)

5) I could neutralize the value: 
![greyed on white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/f6ba2c97-8b63-49fa-a30e-91894d23ee2e)
![greyed on 50](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/7e3c1bc7-e44d-4df4-a5ff-3b2d61261297)
![greyed on black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/b91c021b-169a-41e7-9319-dc34adabb6d2)

And of course, any combo of these options. 

If there are specific locations/background colors, I believe it may look better to manually set them for each (option 1, or upload separate images for each palette). Otherwise, I think I prefer the look of option 4 (outlines).

Let me know! It's easy to adjust these so I'm happy to upload options for all if you want to play around with it.

**Comment by hacceuee** [comment]
A thick outline with a subtle fill may be a nice solution: 
![thick outline white](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/857d2f84-215e-4d3b-8357-2f3d8c340ca8)
![thick outline grey](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/b3c7cd4d-8509-436a-a3f1-487d04bf1239)
![thick outline black](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/65592ddd-5839-49bd-b7d4-664af1cb31c8)

**Comment by fetus-hina** [comment]
"thick outline with a subtle fill" seems a good idea.

**Comment by hacceuee** [comment]
I have updated these in patch 0.0.20: [Link to UI Icons folder] (https://github.com/hacceuee/s3-pixel-icons/tree/98c148c72a977f0206143a2f644c6f661816d910/UI%20Icons)
