### ISSUE TITLE
Salmon Run s3-img-gen

### ISSUE THREAD

**Issue by hacceuee** [hacceuee/s3-pixel-icons#30]
Hey @fetus-hina! As always, I'm looking to make more art 😆 Would you like tide indication pixel art for the Wave 1/2/3 tabs?  I am not sure how many assets s3-img-gen can handle before it is too resource intensive, so I don't want to pile the art on you without asking! 

(Mockup of what I'm thinking) 
![image](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/38e0ce74-9d32-433d-a02a-469a6fe2fba4)

I do not know how the image is currently created, so I can give you this art in a number of different ways to best fit the current code: 

![Options](https://github.com/hacceuee/s3-pixel-icons/assets/54909901/9bf144ee-f1a6-4cca-aaeb-e7f54a5e023b)

1: Just tide indicator
2: Tide indicator + wave tab 
3: Tide indicator + wave tab + black egg count bar 
4: Tide indicator + wave tab + black egg count bar + success or failure indicator

Row "A" is not tilted, Row "B" is tilted to match the current Wave tabs.

**Comment by fetus-hina** [comment]
Thanks for the offer.
It looks "1a" is the best.

First, when creating the "wave cards," the system creates an image that is not tilted.
Then, it is copied to the final image while tilting it 3.5 degrees.
From a designer's point of view, they are created on separate layers.
Therefore, I think A-format is preferable than B-format.

For example, copying without tilting creates this image.
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/3856b71d-21f8-4324-bdf4-2e09ecb12ff2)

Also, extreme tilting produces a funny image 😄 
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/0b009464-fced-4528-9d6a-653e3c548703)

In addition, the display like "4" appears to be preferable, but surprisingly that part will be localized, so the fewer design constraints the better.
As shown in the image above, in Japanese (and Korean), "GJ!" is displayed for a clear result and "NG" for a failed result.
("NG" is a commonly used Japanese-English abbreviation for "Not Good (or No Good)" and is often seen as a contrast to "OK.")

As for "2" or "3", either is fine, but since the possibility of changing the layout in the future cannot be ruled out, I prefer the simpler "1".

**Comment by fetus-hina** [comment]
https://github.com/hacceuee/s3-pixel-icons/commit/747f3252c4492f3eb5dd6ed7df4a64db0c3fa886#diff-04281fd976ac8f06191b7269684a75b1cc2ecdfa5be4ef4f3847b35501eb63ff
Please rename wabe to wave :)

**Comment by fetus-hina** [comment]
![image](https://github.com/hacceuee/s3-pixel-icons/assets/848666/ab96d720-6c2c-48d3-94a5-7f614dc58b4c)
Partially deployed :)

**Comment by hacceuee** [comment]
Awesome! Wabe 😆 I have corrected it!
